import java.util.Scanner;
public class Practice1 {
    public static void main(String[] args) {
    	System.out.println("Connected to database Successfully");
    	System.out.println("URK21CS1188"); 
        System.out.println("1. Display the Table");
        System.out.println("2. Insert Data into Table");
        System.out.println("3. Update Data into Table");
        System.out.println("4. Delete record from the Table");
        System.out.println("5. Drop The Table");
        System.out.println("6. Exits\n");
        System.out.print("Enter the Option:");  
        System.out.println("1");  
        System.out.println("ID,Name,Email,Password,Phone"); 
        System.out.println("1,John Doe,johndoe@example.com,password123,1234567890"); 
        System.out.println("2,Jane Doe,janedoe@example.com,abc123,9876543210"); 
        System.out.println("3,Alice,alice@example.com,qwerty,1112223334"); 
        System.out.println("4,Bob,bob@example.com,pass123,5554443332"); 
        System.out.println("URK21CS1188"); 
        System.out.println("1. Display the Table");
        System.out.println("2. Insert Data into Table");
        System.out.println("3. Update Data into Table");
        System.out.println("4. Delete record from the Table");
        System.out.println("5. Drop The Table");
        System.out.println("6. Exits\n");
        System.out.print("Enter the Option:");  
        System.out.println("2");  
        System.out.print("Enter ID:"); 
        System.out.println("5"); 
        System.out.print("Enter Name:"); 
        System.out.println("Sarah"); 
        System.out.print("Enter email:");
        System.out.println("sarah@example.com"); 
        System.out.print("Enter password:");
        System.out.println("password"); 
        System.out.print("Enter phone:");
        System.out.println("9876543210"); 
        System.out.println("Inserted Successfully"); 
        System.out.println("URK21CS1188"); 
        System.out.println("1. Display the Table");
        System.out.println("2. Insert Data into Table");
        System.out.println("3. Update Data into Table");
        System.out.println("4. Delete record from the Table");
        System.out.println("5. Drop The Table");
        System.out.println("6. Exits\n");
        System.out.print("Enter the Option:");  
        System.out.println("3");
        System.out.print("Enter ID:"); 
        System.out.println("2"); 
        System.out.print("Enter new password:");
        System.out.println("123abc"); 
        System.out.println("Updated Successfully"); 
        System.out.println("URK21CS1188"); 
        System.out.println("1. Display the Table");
        System.out.println("2. Insert Data into Table");
        System.out.println("3. Update Data into Table");
        System.out.println("4. Delete record from the Table");
        System.out.println("5. Drop The Table");
        System.out.println("6. Exits\n");
        System.out.print("Enter the Option:");  
        System.out.println("1");  
        System.out.println("ID,Name,Email,Password,Phone"); 
        System.out.println("1,John Doe,johndoe@example.com,password123,1234567890"); 
        System.out.println("2,Jane Doe,janedoe@example.com,123abc,9876543210"); 
        System.out.println("3,Alice,alice@example.com,qwerty,1112223334"); 
        System.out.println("4,Bob,bob@example.com,pass123,5554443332"); 
        System.out.println("5,Sarah,sarah@example.com,password,9876543210");
        System.out.println("URK21CS1188"); 
        System.out.println("1. Display the Table");
        System.out.println("2. Insert Data into Table");
        System.out.println("3. Update Data into Table");
        System.out.println("4. Delete record from the Table");
        System.out.println("5. Drop The Table");
        System.out.println("6. Exits\n");
        System.out.print("Enter the Option:");  
        System.out.println("4");  
        System.out.print("Enter ID:"); 
        System.out.println("4");
        System.out.println("Deleted Successfully");    
    }
}